#pragma once
#ifndef __SERVER_TO_SERVER_MONITERING_PROTOCOL__
#define __SERVER_TO_SERVER_MONITERING_PROTOCOL__
#define __UNIV_DEVELOPER_

namespace univ_dev
{
	enum SERVER_TYPE
	{
		GAME_SERVER = 1,
		CHAT_SERVER = 2,
		LOGIN_SERVER = 3,
		SERVER_MAX = 4,
	};

	enum GAME_SERVER_MONITERING_TYPE
	{
		G_ON_OFF = 1,
		G_CPU_USAGE = 2,
		G_PRIVATE_BYTES = 3,
		G_SESSION_COUNTS = 4,
		G_AUTH_PLAYER = 5,
		G_GAME_PLAYER = 6,
		G_ACCEPT_TPS = 7,
		G_PACKET_RECV_TPS = 8,
		G_PACKET_SEND_TPS = 9,
		G_DB_WRITE_TPS = 10,
		G_DB_MSG_QUEUE_SIZE = 11,
		G_AUTH_THREAD_FPS = 12,
		G_GAME_THREAD_FPS = 13,
		G_PACKET_POOL_USAGE = 14,
		G_MAX = 15
	};

	enum CHAT_SERVER_MONITERING_TYPE
	{
		C_ON_OFF = 1,
		C_CPU_USAGE = 2,
		C_PRIVATE_BYTES = 3,
		C_SESSION_COUNTS = 4,
		C_PLAYER_COUNTS = 5,
		C_UPDATE_TPS = 6,
		C_PACKET_POOL_USAGE = 7,
		C_UPDATE_MSG_QUEUE_SIZE = 8,
		C_MAX = 9
	};

	enum LOGIN_SERVER_MONITERING_TYPE
	{
		L_ON_OFF = 1,
		L_CPU_USAGE = 2,
		L_PRIVATE_BYTES = 3,
		L_SESSION_COUNTS = 4,
		L_AUTH_TPS = 5,
		L_PACKET_POOL_USAGE = 6,
		L_MAX = 7
	};
}


#endif // !__SERVER_TO_SERVER_MONITERING_PROTOCOL__
